### ISSUE TITLE
State machines with TypeScript

### ISSUE THREAD

**Issue by karol-majewski** [WrocTypeScript/talks#11]
### What should the talk be about?

- What are they?
- Do they really help?
- Are there any good libraries out there?

### Why is that important?

As client-side-only applications become more advanced, the problem of state management has become real. One of the possible answers to that problem is using finite state machines](https://github.com/voodooattack/when-ts).

### Who will learn from it?

Developers who have to manage a complex state.

**Comment by alexmdodge** [comment]
@karol-majewski I use FSMs in my current product, you can sign me up for this one for either the January or February slot depending on who's going.

**Comment by karol-majewski** [comment]
@alexmdodge Sure thing, it's yours. 🙇

**Comment by karol-majewski** [comment]
Scheduled for March! 🙇
