### ISSUE TITLE
TypeScript Library Cookbook

### ISSUE THREAD

**Issue by karol-majewski** [WrocTypeScript/talks#15]
### What should the talk be about?

- How to configure your build pipeline
- How to export good type definitions
- How to make your library work with different versions of TypeScript

### Why is that important?

[46% of npm users are using TypeScript](https://twitter.com/casesandberg/status/1038626258362327041). It's becoming a _de facto_ standard.

### Who will learn from it?

Library authors.

**Comment by karol-majewski** [comment]
@chodorowicz sounds like something you'd like to talk about?

**Comment by chodorowicz** [comment]
Yeah, sounds good! I will take it 👍

**Comment by karol-majewski** [comment]
Example questions:

- What if the types in your library make use of the latest TypeScript (conditional types, bigint etc.), but your users are still using an older version?
- What `target` should you choose in `tsconfig.json`?
- Should you be using `importHelpers` and `noEmitHelpers`? What about `downlevelIteration`?
- What is `declarationMap`?

**Comment by karol-majewski** [comment]
Another example question: if your library is just about types, not executable code (like https://github.com/bterlson/strict-event-emitter-types), what should be your `main` in `package.json` be (so it conforms to the rules of npm)?

**Comment by chodorowicz** [comment]
Cool, thanks @karol-majewski. I will try to take those into account and be ready to give answers 🙂

**Comment by karol-majewski** [comment]
Don't thank me @chodorowicz, I'm doing it for purely selfish reasons! 😛
