### ISSUE TITLE
Contributing to the TypeScript ecosystem

### ISSUE THREAD

**Issue by karol-majewski** [WrocTypeScript/talks#17]
### What should the talk be about?

- Contributing to DefinitelyTyped
- Contributing to TSLint and custom rulesets
- Popular projects using TypeScript
- Great libraries looking for maintainers

### Why is that important?

Cause it's cool to give back 🙌 

### Who will learn from it?

Developers familiar with TypeScript, but not familiar with contributing to open-source software.

**Comment by evanSe** [comment]
- Your full name: Evan Seaward
- Target audience (beginner/intermediate/advanced/**everyone**):
- Estimated duration: 30 minutes
- Keywords: OSS, typescript, contributing

# Coding Adventure: Contributing to the TypeScript ecosystem 

## The talk

### One-sentence summary
Coding adventure in the TypeScript ecosystem.

### What's the format — is it a case study, a live coding session, a workshop or something else?
lecture/live coding/coding adventure  

### Tell us more about the talk
Come with me on a a coding adventure where I attempt to contribute to the typescript ecosystem. Let’s explore how one goes about "contributing" and some of the good and bad things one might come across...

## You

### A few words about yourself
Australian Senior Front-end Developer escaping the inhospitable 🔥 🐍 🦈 things of Australia working here in Wrocław at Fox Heap. Currently working with React & TypeScript.

### How can we find you on social media?
https://twitter.com/seawardevan
https://evanseaward.com 

### Would you be willing to have a Q/A session after the talk?
Of course 😉 

### Do you mind if we record the event?
@karol-majewski if recording is not possible, maybe we can get some screen recordings going + audio?

### Is there anything we can help you with?
🍻

**Comment by evanSe** [comment]
For February

**Comment by hasparus** [comment]
If we won't manage to organize proper recording, I'll try to record with a smartphone on a tripod for this lo-fi old-school vibe.

**Comment by evanSe** [comment]
@hasparus  Now that is the type of ＩＤΞΛ I like

**Comment by orta** [comment]
Also adding a translation to the typescript website is a great way to do this https://github.com/microsoft/TypeScript-Website/issues/100 ;)

**Comment by hasparus** [comment]
Big thanks for the talks Evan! I loved the anecdote about "unkown" :D
