### ISSUE TITLE
Developing Visual Studio Code extensions

### ISSUE THREAD

**Issue by karol-majewski** [WrocTypeScript/talks#29]
### What should the talk be about?

- How to develop, test, and publish one to Visual Studio Marketplace
- Are there any tools that can help you? (boilerplate repositories, generators)

### Why is that important?

When you're developing a tool, having it as a Visual Studio Code extension lowers the entry barrier for your future consumers.

### Who will learn from it?

Tool authors and maintainers.

**Comment by karol-majewski** [comment]
@blackdahila was this something you'd like to talk about?

**Comment by blackdahila** [comment]
Yes, as a lighting talk

**Comment by karol-majewski** [comment]
Done in #32.
