### ISSUE TITLE
Handling transient errors with tryMax library 

### ISSUE THREAD

**Issue by marcinporebski** [WrocTypeScript/talks#30]
- **Your full name**: Marcin Porębski
- **Target audience** (beginner/intermediate/advanced/everyone): everyone
- **Estimated duration**: 10 mins (lightning talk)
- **Keywords**: try, retry, transient error, exponentional backoff

# Handling transient errors with tryMax library 

### One-sentence summary

The transient errors are common in cloud computing while handling them can mess the code a little bit... but not necessarily ;-)

### What's the format — is it a case study, a live coding session, a workshop or something else?

Case study + live coding.

### Tell us more about the talk

This will be a talk about way to handle transient errors on the example of tryMax library which I wrote myself. The library itself is not yet very popular, but I found it very suitable for the use-case. It's written purely in TS therefore I find it good fit for the meetup.

### A few words about yourself
https://www.linkedin.com/in/marcin-porebski

### Would you be willing to have a Q/A session after the talk?
Yes

**Comment by blackdahila** [comment]
Hi! Thanks for your talk proposal. You are welcome to perform at the meetup that is due to January 30. If you have any questions, feel free to ask us.

**Comment by marcinporebski** [comment]
@blackdahila can you provide me details where shall I enter the venue? I mean I have not registered as atendee, and as I reckon I have to enter other way?

**Comment by blackdahila** [comment]
Can we take this conversation to hello@typescript.community to share phone numbers? We could contact this way and provide you with the details.

**Comment by karol-majewski** [comment]
Thank you for your talk today! It was a privilege to have someone that senior talk for us. If you'd like to talk some more about this topic (or any other topic!), please let us know.
