### ISSUE TITLE
⚡ Functional Composition with Static Types in TypeScript ⚡

### ISSUE THREAD

**Issue by ducin** [WrocTypeScript/talks#31]
- **Your full name**: Tomasz Ducin
- **Target audience** (beginner/intermediate/advanced/everyone): everyone
- **Estimated duration**: 30-40 minutes
- **Keywords**: FP, TS

# ⚡ Functional Composition with Static Types in TypeScript ⚡

### One-sentence summary

No need to mention that FP is hot nowadays, so many tools rely on it, including react, redux, rxjs, ramda etc. But when it comes down to: what can I actually do with it? Or: how can I make it work seamlessly with TypeScript and static typing? - then it's not so obvious anymore. In this session we'll do some practical and statically-typed FP.

### What's the format

50% lecture, 50% live coding.
Could also be a workshop 😎

### Tell us more about the talk

Theory - on how, why, the philosophy, comparison to OOP.
Practice - usecases, how we can use it the next day in our projects.

### A few words about yourself

Independent Consultant, Architect and a Developer. Your JavaScript world guide. Speaker at European and Polish conferences. A trainer with passion to explain how things work and to avoid overcomplicated solutions, as well as making unnecessary decisions. A critic of buzzwords and overexcitement around certain tools.
Ex-theatre actor. 4 espressos a day.

### Would you be willing to have a Q/A session after the talk?

Sure

### Is there anything we can help you with?

I need only a working projector.

**Comment by karol-majewski** [comment]
> I need only a working projector.

Like a boss! 😎 Thank you for your proposal. We are already excited about it.

**Comment by karol-majewski** [comment]
Thank you for your talk @ducin!
