### ISSUE TITLE
React with TypeScript

### ISSUE THREAD

**Issue by hasparus** [WrocTypeScript/talks#33]
- **Piotr Pietrzak**:
- **Target audience** (beginner/intermediate/advanced/everyone): everyone
- **Estimated duration**: 30min
- **Keywords**: React, TypeScript

# React with TypeScript

### One-sentence summary

I'll tak about **why** and **how**  to use TypeScript in your React apps.

### What's the format — is it a case study, a live coding session, a workshop or something else?

Case study (maybe with a little bit of live coding).

### Tell us more about the talk

Types. React. Even more types. Mediocre jokes.
I'll tak about **why** and **how**  to use TypeScript in your React apps.
We're going to look at some _tsx_ code, talk about, maybe break it.

### A few words about yourself

I'm HMR and autocomplete addict working at Chop-Chop. I love building fun stuff.

### Would you be willing to have a Q/A session after the talk?

Sure I do!

### Is there anything we can help you with?

🤔

I'm gonna need a chopper and some red carpet :)

**Comment by karol-majewski** [comment]
Thanks for speaking for us today! So great to see the bleeding-edge features of React in a real-life scenario. And to see they are fully compatible with React. Great talk!
