### ISSUE TITLE
Linting TypeScript code

### ISSUE THREAD

**Issue by karol-majewski** [WrocTypeScript/talks#35]
### What should the talk be about?

- TSLint or ESLint? What are the differences?
- How do they work with Prettier?
- Are there alternatives to these two?
- Can I use one tool for JavaScript, TypeScript, [and GraphQL](http://artsy.github.io/blog/2019/01/29/from-tslint-to-eslint/)?
- What setup do you recommend?

### Why is that important?

The recent plans for ESLint seem to have stirred the situation. It's not clear which tools should one use now. Is it worth switching over?

### Who will learn from it?

Everyone.

**Comment by hasparus** [comment]
More ideas:
- eslint-typescript -- is it ready to use? How to configure it alongside your JS eslint config while migrating apps (I have a good example).
- [Marie Kondo Your Lint Config](https://overreacted.io/writing-resilient-components/#marie-kondo-your-lint-config)
- Wotan -- https://github.com/fimbullinter/wotan

**Comment by karol-majewski** [comment]
+ what is the timeline for TSLint deprecation:

https://github.com/microsoft/tslint-microsoft-contrib/issues/876

**Comment by hasparus** [comment]
> There are so many JavaScript linters out there.
Which one should we use?
How do I configure ESLint for TypeScript?
What the heck is Wotan?
Won't linter slow me down?
Why are these rules so annoying?
How do I create a linter config package for my team?
There are so many questions and even more opinions.
Let's argue about them loudly while drinking beer.

Agenda:
  - How to avoid "Best Practices" and become friends with your linter.  
  - Can I already ditch TSLint for ESLint. Does it hurt?
  - What the heck is Wotan?
  - How to add `typescript-eslint` rules to your JS eslint config.
