### ISSUE TITLE
"Write different" - the functional reactive nature of Node.js in Marble.js

### ISSUE THREAD

**Issue by JozefFlakus** [WrocTypeScript/talks#39]
- **Your full name**: Józef Flakus
- **Target audience** (beginner/intermediate/advanced/everyone): intermediate/advanced
- **Estimated duration**: 30-40 minutes
- **Keywords**: FRP, TS,  Node.js

# "Write different" - the functional reactive nature of Node.js in Marble.js

### One-sentence summary
How to write server-side with functional reactive data flow in mind using Marble.js framework.

### What's the format — is it a case study, a live coding session, a workshop or something else?
100% lecture

### Tell us more about the talk
Reactive programming is not just a buzzword but nowadays is a de facto standard for building web apps on the frontend. On the Node.js, the concept is still not so popular as we might think. During the lecture I'll try to present the functional reactive programming paradigm in the JS world, not hiding behind the famous "monadic topic". Next I will present the main idea and examples of usage in the Marble.js framework.

### A few words about yourself
For 4 years Software Developer @ [Boldare](https://www.boldare.com/). Marble.js author, functional reactive hipster, pedant with a little of OCD. There are rumors that he can talk over and over again about only three things - functional programming, reactive functional programming and Marble.js.

### Would you be willing to have a Q/A session after the talk?
Why not?

### How can we find you on social media?
https://twitter.com/jozflakus
https://twitter.com/marble_js
https://medium.com/@jflakus/marble-js-when-node-js-meets-rxjs-da2764b7ca9b
https://medium.com/@jflakus/marble-2-reactive-better-functional-stronger-5924119d3098

### Is there anything we can help you with?
A microphone + projector 💪

**Comment by karol-majewski** [comment]
This sounds fantastic @JozefFlakus! Would you be willing to give the talk at the March 27th meetup?

**Comment by JozefFlakus** [comment]
Sure thing!

**Comment by karol-majewski** [comment]
Sold!

**Comment by karol-majewski** [comment]
Thank you for giving the talk @JozefFlakus!

**Comment by JozefFlakus** [comment]
Here are slides from my last talk:
https://speakerdeck.com/jozefflakus/the-functional-reactive-nature-of-marble-dot-js

Cheers! 💪
