### ISSUE TITLE
WAT TypeScript

### ISSUE THREAD

**Issue by karol-majewski** [WrocTypeScript/talks#40]
- **Your full name**: Karol Majewski
- **Target audience** (beginner/intermediate/advanced/everyone): beginners
- **Estimated duration**: 30 minutes
- **Keywords**: syntax, concepts, heuristics, wtf 🤔

# WAT TypeScript (TypeScript Syntax Demystified)

### One-sentence summary

Some of the most confusing parts of TypeScript explained.

### What's the format — is it a case study, a live coding session, a workshop or something else?

A lecture.

### Tell us more about the talk

There is a gap between what TypeScript docs say and what you actually encounter in real life. TypeScript adds new keywords, new concepts, and some of them don't make much sense at first. Some of them you need to learn the hard way. I'm here to change that.

### A few words about yourself

UI engineer with a focus on typed functional programming, static analysis, and developer tools. have been working with TypeScript for over 2 years and made all kinds of mistakes. Currently working for Unsplash.

### Would you be willing to have a Q/A session after the talk?

Hell yeah.

### How can we find you on social media?

Well, https://twitter.com/wroctypescript is a start. https://twitter.com/karoljmajewski if you want my personal profile.

### Is there anything we can help you with?

Nope, I'm good.

**Comment by blackdahila** [comment]
Hi Karol! It would be great to hear you talk on the next meetup! Can't wait 🚀
