### ISSUE TITLE
Matryoshka Code Rant

### ISSUE THREAD

**Issue by hasparus** [WrocTypeScript/talks#41]
- **Full name**: Piotr Monwid-Olechnowicz
- **Target audience**: Everyone
- **Estimated duration**: 15 minutes
- **Keywords**: dry code, moist code, hot code, wet code 🥁

# Matryoshka Code Rant

### One-sentence summary
I'm gonna rant about matryoshka code, DRY as dunes of Arrakis and utmost unpleasant to work with.

### What's the format — is it a case study, a live coding session, a workshop or something else?
lecture / case study

### Tell us more about the talk
![matryoshkas](https://images-na.ssl-images-amazon.com/images/I/5186qD8N%2BpL._SX466_.jpg)
I'm gonna rant about matryoshka code, DRY as dunes of Arrakis and utmost unpleasant to work with. Have you heard about it? Are you _guilty_ of writing it? I'm going to describe the problem and propose few ideas of how to deal with it.

Disclaimer: Most opinions here are mine, some of them are John Carmack's.

### A few words about yourself

Laptop hobo. Honest programming enthusiast. Software Gardener at Chop-Chop.

### How can we find you on social media?
https://twitter.com/hasparus

### Would you be willing to have a Q/A session after the talk?
👍

### Do you mind if we record the event?
Nah, It's cool.

### Is there anything we can help you with?
Don't. Write. Matryoshka. Code. Ever again.

**Comment by karol-majewski** [comment]
![image](https://user-images.githubusercontent.com/20233319/55629071-92c9ba80-57b2-11e9-8fd7-f57bb1c7c7e4.png)

**Comment by karol-majewski** [comment]
Thanks!
