### ISSUE TITLE
“The things I always do when I start a new project” - Bootstrapping CreateReactApp with TypeScript. 

### ISSUE THREAD

**Issue by maszynka** [WrocTypeScript/talks#42]
### What should the talk be about?
“The things I always do when I start a new project” - Bootstrapping CreateReactApp with TypeScript. 
### Why is that important?
To show real bootstrap with simple app that we all know and extend it a bit.
### Who will learn from it?
Everyone. Beginners will get straight on right track seniors might reconsider their approaches (or suggest different).

**Comment by karol-majewski** [comment]
I'm copy-pasting from Meetup so nothing gets lost:

> What about taking create-react-app with typescript and just making a quick comment about best approaches and finishing within about 45-30 minutes with properly written app (just a bit bigger than source one). And next part of meetup with more advanced stuff.

> It could include structuring your types, adding useful helper types and modeling your global variables.

**Comment by karol-majewski** [comment]
Possibly related to #8 since the _first steps_ apply in both cases.

**Comment by karol-majewski** [comment]
Done in #45
