### ISSUE TITLE
Creating command line apps with ink 🌈

### ISSUE THREAD

**Issue by beerose** [WrocTypeScript/talks#43]
- **Aleksandra Sikora**
- **Target audience**: everyone
- **Estimated duration**: 20 min
- **Keywords**: command-line app, react, ink

# Creating command-line apps with ink 🌈

## The talk

The talk will be an introduction to Ink — a convenient way of creating interactive command-line interfaces. No more dealing with stdin/stdout on your own, no more building state management logic from scratch. We can create awesome CLI apps with React and leverage the same React's features we use when building web apps.

### One-sentence summary

Creating awesome CLI apps with good ol' React.

### What's the format — is it a case study, a live coding session, a workshop or something else?

Lecture, maybe live coding.

### Tell us more about the talk

It will be cool. 

### How can we find you on social media?

https://twitter.com/aleksandrasays

### Would you be willing to have a Q/A session after the talk?

Yes

### Do you mind if we record the event?

Nope.

**Comment by blackdahila** [comment]
It's not about the April meetup, though.
