### ISSUE TITLE
Path to strict type checking

### ISSUE THREAD

**Issue by chodorowicz** [WrocTypeScript/talks#44]
- **Jakub Chodorowicz**:
- **Target audience**: intermediate
- **Estimated duration**: 10 minutes
- **Keywords**: strict type checking, migration

# Path to strict type checking

### One-sentence summary

This lightning talk will present how code base with loose config (no strict setting) could be gradually migrated to strict one. 

### What's the format — is it a case study, a live coding session, a workshop or something else?

case study

### Tell us more about the talk

It's difficult to overestimate the benefits of having strict config of TypeScript compiler. Unfortunately many code bases have their strict settings turned off. It often happens in case of old JS code bases which were migrated to TypeScript. The recent case of VS Code base which was migrated to `strictNullChecks` will be used an example of approach how this kind of migration can be gradually performed in large code base.

### A few words about yourself

Jakub is software engineer working currently in Collibra office in Wroclaw. He's fighting ⚔ mainly on front-end front and using tools like TypeScript and React to build maintainable and bulletproof 🛡 web apps. Always ready to talk tech and life topics while sipping some yerba mate.

### How can we find you on social media?

https://twitter.com/chodorowicz

### Would you be willing to have a Q/A session after the talk?

Sure

### Do you mind if we record the event?

No problemo

### Is there anything we can help you with?

All good.

**Comment by karol-majewski** [comment]
Sold!

**Comment by karol-majewski** [comment]
Thanks!
