### ISSUE TITLE
Building Real-World React/Redux Applications with Static Typing using TypeScript

### ISSUE THREAD

**Issue by piotrwitek** [WrocTypeScript/talks#45]
- **Your full name**: Piotr Witek
- **Target audience** (beginner/intermediate/advanced/everyone): everyone
- **Estimated duration**: 50min + Questions
- **Keywords**: react, redux, typescript, realworld, create-react-app, example, application

# Building Real-World React/Redux Applications with Static Typing using TypeScript

### One-sentence summary
Learn to build Real-World React/Redux Applications with Static Typing using TypeScript

### What's the format — is it a case study, a live coding session, a workshop or something else?
Live coding

### Tell us more about the talk
Based on patterns from my "React & Redux in TypeScript - Static Typing Guide" I will guide you through the process of creating a Type-Safe Single Page Application from scratch. Starting from an empty `create-react-app` we’ll be adding various application layers commonly found in the front-end architectures. We’ll be modeling the data of our Domain using Types, we’ll add mocked application services for communication with an API (like for user authentication) and finally add some core application features. We will end up with a fully functional, maintainable and completely type-safe application that could be a solid base for your next personal project.

### A few words about yourself
WIP

### How can we find you on social media?
github.com/piotrwitek
twitter.com/piotrekwitek

### Would you be willing to have a Q/A session after the talk?
Yes

### Do you mind if we record the event?
I'm ok

**Comment by karol-majewski** [comment]
Answers #42.

**Comment by hasparus** [comment]
🔥

**Comment by karol-majewski** [comment]
Thank you for giving the talk @piotrwitek!
