### ISSUE TITLE
Type safety at runtime with JSON decoders

### ISSUE THREAD

**Issue by kajetansw** [WrocTypeScript/talks#48]
- **Your full name**: Kajetan Świątek
- **Target audience**: everyone
- **Estimated duration**: 5-10 min
- **Keywords**: decoder runtime type safety

# Type safety at runtime with JSON decoders

### One-sentence summary 
A brief introduction to JSON decoders in TypeScript.

### What's the format — is it a case study, a live coding session, a workshop or something else?
Lighting talk.

### Tell us more about the talk
As we all know, TypeScript’s adds static typing and compile-time type checking to our beloved JavaScript. But wait… What about run-time? How do I know, that my application still gets valid data from the external REST API?
Don’t worry, JSON decoders come to the rescue!
During this talk, you’ll get a brief introduction to the concept of JSON decoders and how to use them in TypeScript.

### A few words about yourself
Junior Angular Developer at Aptitude Software. Coding nerd. Learning-new-stuff lover. Hears coding buzzwords from a mile away and comes right away to join the talk.

### How can we find you on social media?
On the Twitter @kajetansw and on my blog at dev-self-start.blogspot.com.

### Would you be willing to have a Q/A session after the talk?
Yes.

### Do you mind if we record the event?
Not at all. 

### Is there anything we can help you with?
I would like to know how would you like to get my presentation (e.g. via email). I don’t think that bringing my own laptop is necessary for a 5-minute talk. I prefer slides.com for my presentation, so it will be in the .html format.

**Comment by karol-majewski** [comment]
Sweet @kajetansw! Thanks for your submission.

As for bringing your own machine: if you don't want to have your laptop with you, we can find one for you.

Do you think it would be possible to deliver your talk in 5 minutes? We decided to stick with such a constraint in order to squeeze more topics at our September meetup.

**Comment by kajetansw** [comment]
I generally think that it is a good idea to set up one laptop than to set up different machines every 5 minutes. That way you may save some time. But... It's just a thought ;)

It will be a brief intro with a ~30-line example within a couple of slides. I think I can deliver.

**Comment by karol-majewski** [comment]
> I generally think that it is a good idea to set up one laptop

I do think so, too — however, we always do what our speakers think is best. Old habits and all that. ;-)

Perfect! Please let us know if you have any questions.

As for submitting the slides: you can send them to hello@typescript.community or just access them in the browser if they will be online.
