### ISSUE TITLE
WebAssembly with typescript 

### ISSUE THREAD

**Issue by evanSe** [WrocTypeScript/talks#57]
- **Your full name**: Evan Seaward
- **Target audience** everyone
- **Estimated duration**: 5 min
- **Keywords**: WebAssembly, Typescript

# WebAssembly with typescript 

### One-sentence summary
A introduction to the use of Typescript to generate WebAssembly modules

### What's the format — is it a case study, a live coding session, a workshop or something else?
Lightning talk

### Tell us more about the talk
As we have all probably heard by now WebAssembly is being heralded a game changer for the web, In this talk I shall demystify the process of creating WebAssembly modules with typescript, Why you should and when you should not.

### A few words about yourself
Senior Front-end developer at Fox Heap, working with React and Typescript. Enjoys dabbling around with IoT (Robotics, Sensors).

### How can we find you on social media?
Can check me out at https://github.com/evanSe/ & follow me at https://twitter.com/EvanOnes

### Would you be willing to have a Q/A session after the talk?
Would love to

### Do you mind if we record the event?
Record away

**Comment by karol-majewski** [comment]
Hello @evanSe and thank you for your proposal!

This sounds fantastic. We would be delighted to have you on our September 25th meetup.

If that's okay with you, I can add you to the agenda immediately.

**Comment by evanSe** [comment]
@karol-majewski  25th September meetup sounds great, Thanks.

**Comment by karol-majewski** [comment]
@evanSe Perfect!

**Comment by karol-majewski** [comment]
Hey @evanSe, is @EvanOnes your Twitter handle? There doesn't seem to be any account under that name.

**Comment by karol-majewski** [comment]
@evanSe Perfect! I just updated it [here](https://github.com/WrocTypeScript/past-events/blob/master/2019-09-25.md). Thanks!
