### ISSUE TITLE
Persistent data structures thanks to recursive type aliases

### ISSUE THREAD

**Issue by blackdahila** [WrocTypeScript/talks#58]
- **Your full name**: Aleksandra Sikora
- **Target audience**: intermediate/advanced
- **Estimated duration**: ~20min
- **Keywords**: data structures, type aliases, immutability

# Persistent data structures thanks to recursive type aliases

### One-sentence summary

TBD

### What's the format — is it a case study, a live coding session, a workshop or something else?

Case study

### Tell us more about the talk

TBD

### A few words about yourself

Full-stack developer at Ingrid. Working with Go and TypeScript. Interested in functional programming.

### How can we find you on social media?

https://twitter.com/aleksandrasays

### Do you mind if we record the event?

Not at all.

**Comment by karol-majewski** [comment]
Thank you for your talk, Ola!
