### ISSUE TITLE
Power of Preconditions: Why assertion signatures are huge for me

### ISSUE THREAD

**Issue by hasparus** [WrocTypeScript/talks#60]
- **Your full name**: Piotr Monwid-Olechnowicz
- **Target audience** (beginner/**intermediate**/advanced/everyone):
- **Estimated duration**: 30 minutes
- **Keywords**: assert, 3.7, exception, error, either, preconditions, react 

# Power of Preconditions: Why assertion signatures are huge for me
### One-sentence summary

I'm in reciprocated love with assertion signatures and I'm gonna show you why.

### What's the format — is it a case study, a live coding session, a workshop or something else?

a lecture

### Tell us more about the talk

TypeScript 3.7 brings us an amazing tool to concisely write preconditions that can't be described in a function signature. With [assertion signatures](https://devblogs.microsoft.com/typescript/announcing-typescript-3-7-beta/) we can get rid of these ugly `if (not cool) throw new AssertionError("totally not cool")` blocks.

We're gonna talk about partial and total functions, returning vs throwing errors and I'll show you how assertion signatures make my React code safer.

### A few words about yourself

I write stupid stuff fast and I trust that the type system will protect me from myself.

### How can we find you on social media?

https://twitter.com/hasparus
Beware: I retweet bad dev jokes[**.**](https://twitter.com/markdalgleish/status/1186413157276762112)

### Would you be willing to have a Q/A session after the talk?

✅

### Do you mind if we record the event?

Nah. Make me famous 💃

### Is there anything we can help you with?

I'd be grateful if my talk weren't the only one on the next meetup.

**Comment by karol-majewski** [comment]
Thanks a lot! Make sure to share the _mom joke_.

**Comment by hasparus** [comment]
> Thanks a lot! Make sure to share the mom joke.

Here you go.
https://twitter.com/hasparus/status/1189852901524594688
