### ISSUE TITLE
Dive into Optional Chaining and Nullish Coalescing

### ISSUE THREAD

**Issue by evanSe** [WrocTypeScript/talks#61]
- **Your full name**: Evan Seaward
- **Target audience** (beginner/intermediate/advanced/**everyone**):
- **Estimated duration**: 10-15 minutes
- **Keywords**: null, optional, chaining, nullish, coalescing.

# Dive into Optional Chaining and Nullish Coalescing

### One-sentence summary
A much loved feature of other languages makes its debut in typescript 3.7, lets explore.

### What's the format — is it a case study, a live coding session, a workshop or something else?
lecture/live coding

### Tell us more about the talk
After entering stage 3 of proposal Optional Chaining and Nullish Coalescing has arrived in typescript 3.7, lets have a deep dive into these new features and explore how this will improve your code.

### A few words about yourself
Senior Front-end Aussie developer working at Fox Heap here in Wrocław, currently developing in React and Typescript.

### How can we find you on social media?
https://twitter.com/seawardevan
Hopefully I tweet something one day.

### Would you be willing to have a Q/A session after the talk?
Gladly
### Do you mind if we record the event?
Keep em rolling.

### Is there anything we can help you with?
🍻 😉

**Comment by karol-majewski** [comment]
Wonderful @evanSe! Thank you for your proposal.

Just to make sure: are you okay with giving the talk on our October meetup (Oct 30th)?

**Comment by karol-majewski** [comment]
Sold!

**Comment by karol-majewski** [comment]
Hey @evanSe, would you like to join the official TypeScript Community Discord channel? We have a room called `wrocław-typescript` where we discuss our activities. I have prepared an invitation for you:

https://discord.gg/mG5ZuKd

**Comment by karol-majewski** [comment]
Thank you for giving the talk @evanSe!
