### ISSUE TITLE
Type Guards - Strongly Typing Flexible Code

### ISSUE THREAD

**Issue by alexmdodge** [WrocTypeScript/talks#63]
- **Your full name**: Alex Dodge
- **Target audience** (beginner/intermediate/advanced/everyone): Everyone (I'll build them up)
- **Estimated duration**: 15 - 30 minutes
- **Keywords**: type guards, predicates, instanceof, branching, flexible apis, typeof

# Type Guards - Strongly Typing Flexible Code

### One-sentence summary
Type guards are expressions which allow us to branch our code based on the shape of a union type without having to assert every time we use it.

### What's the format — is it a case study, a live coding session, a workshop or something else?
Case study style, where we investigate how we can use type guards to provide flexible interfaces.

### Tell us more about the talk
We'll go into the various kinds of type guards, the benefits and pitfalls, and tips when incorporating them into a real codebase. In the process we'll refactor some code to see how they make our lives easier.

### A few words about yourself
(Same as before)

### How can we find you on social media?
(Same as before)

### Would you be willing to have a Q/A session after the talk?
Yes

### Do you mind if we record the event?
I can record my screen as well 👍

**Comment by karol-majewski** [comment]
Perfect @alexmdodge, thanks for your proposal!

When would you like to deliver that one?

**Comment by alexmdodge** [comment]
Happy to present this at the next one if there is room 👍

**Comment by karol-majewski** [comment]
@alexmdodge We're in two minds as to whether the next event should take place in December or in January. If we opted in for December, would that be soon for you?

**Comment by alexmdodge** [comment]
Shouldn't make a difference! I already have most of the presentation as I've presented this previously, I just need to clean it up and add a couple things. So it can be last minute.

**Comment by karol-majewski** [comment]
Thank you @alexmdodge!
