### ISSUE TITLE
What are these decorators?

### ISSUE THREAD

**Issue by mat3e** [WrocTypeScript/talks#65]
- **Your full name**: Mateusz Chrzonstowski
- **Target audience** (beginner/intermediate/advanced/everyone): everyone
- **Estimated duration**: 30 min
- **Keywords**: decorators, Angular, evolution

# What are these decorators?

### One-sentence summary
I want to show what the first version of decorators was about and how to build them.

### What's the format — is it a case study, a live coding session, a workshop or something else?
Presentation with executable code examples.

### Tell us more about the talk
I think every front-end developer has seen code written in Angular. This framework has certainly introduced decorators to the mainstream, but it is not their only use. We write things that begin with "@" also in MobX, "react-redux" and there are also examples from Vue and Stencil.

I want to show what the first version of decorators was about and how to build them. Moreover, I will provide the overview of the current decorators proposal.

### A few words about yourself

I help achieving better results by creating computer programs and by sharing my knowledge about how to program. I combine an engineering approach with a smile and a business focus.

Software Engineer and IT Trainer focused on front-end and integration technologies, with a relevant full-stack experience. Since 2013 I've been making a living by programming.

I share my knowledge at meetups, job fairs and conferences.

I'm skilled in JavaScript, Java, Arduino and in addition to programming and knowledge sharing, I'm truly interested in AI, technology, Dragon Ball, MMA and the strategies of the big companies (Frightful5).

### How can we find you on social media?

- LinkedIn: https://www.linkedin.com/in/mateusz-chrzonstowski/
- GitHub: https://github.com/mat3e/
- Twitter: https://twitter.com/_mat3e_
- Udemy: https://www.udemy.com/user/mateusz-chrzonstowski/
- Reddit: https://www.reddit.com/user/_mat3e_

### Would you be willing to have a Q/A session after the talk?

No problem.

### Do you mind if we record the event?

I like recorded events.

### Is there anything we can help you with?

Nope.

**Comment by karol-majewski** [comment]
Sold, thank you @mat3e ! 👏

**Comment by mat3e** [comment]
Slides: https://mat3e.github.io/talks/decorators/wroc-ts.html

**Comment by karol-majewski** [comment]
Linked to the slides [here](https://github.com/WrocTypeScript/past-events/blob/master/2020-01-29.md) and on the [meetup page](https://www.meetup.com/pl-PL/WrocTypeScript/events/sjzhvqybccbdc/) 👍
