### ISSUE TITLE
Level up your TypeScript code by using ******

### ISSUE THREAD

**Issue by kajetansw** [WrocTypeScript/talks#67]
- **Your full name**: Kajetan Świątek
- **Target audience** intermediate
- **Estimated duration**: 30min
- **Keywords**: 

# Level up your TypeScript code by using ******

### One-sentence summary
My take on the idea of improving our everyday TypeScript code.

### What's the format — is it a case study, a live coding session, a workshop or something else?
~30min presentation.

### Tell us more about the talk
Many developers strive to achieve perfection, that is both a blessing and a curse of our craft. For that, we look for ways to improve our workflow and our experience with various technologies.

During this presentation, I will offer you my secret sauce for improving our TypeScript code and how to go even beyond that!

### A few words about yourself
Front-end developer at Aptitude Software. Recent functional programming enthusiast. Known as the harshest code reviewer in his team (for some unknown reason). Hears coding buzzwords from a mile away and comes right away to join the talk.

### How can we find you on social media?
Twitter [@kajetansw](https://twitter.com/kajetansw)

### Would you be willing to have a Q/A session after the talk?
Sure.

### Do you mind if we record the event?
I don't mind.

### Is there anything we can help you with?
No, thanks :)

**Comment by karol-majewski** [comment]
Thanks for the proposal @kajetansw! Would that be okay if I scheduled it for the March event?

**Comment by kajetansw** [comment]
Hey! That would be great!
Thanks!


czw., 27 lut 2020, 13:14 użytkownik Karol Majewski <notifications@github.com>
napisał:
