### ISSUE TITLE
TypeScript myths debunked

### ISSUE THREAD

**Issue by krzysztofzuraw** [WrocTypeScript/talks#7]
- **Your full name**: Krzysztof Żuraw
- **Target audience** everyone
- **Estimated duration**: 30min
- **Keywords**: myths, expalined

# TypeScript myths debunked

## The talk

In my talk I want to present my take on popular myths about TypeScript and its ecosystem. I want to
talk about testing, frameworks, static types, TypeScript ecosystem. This won't be a rant to anybody -
I will give my arguments for or against common myths that are connected with TypeScript.

### One-sentence summary

Let's explain the most common myths about TypeScript.

### What's the format — is it a case study, a live coding session, a workshop or something else?

My take about given subject.

### A few words about yourself

I work as a frontend developer at Ingrid. For my work I really enjoy using TypeScript, React & Redux. If I am not coding I'm really into discovering awesome restaurants, enjoying good specialty coffee and doing some street workout.

### Would you be willing to have a Q/A session after the talk?

Yes

### Is there anything we can help you with?

No

**Comment by karol-majewski** [comment]
Thanks for the great delivery and for the lesson in arts! :D
