### ISSUE TITLE
Property based testing: from zero to hero

### ISSUE THREAD

**Issue by dubzzz** [WrocTypeScript/talks#71]
- **Your full name**: Nicolas Dubien
- **Target audience** (beginner/intermediate/advanced/everyone): everyone
- **Estimated duration**: 30 minutes
- **Keywords**: testing, typescript

# Property based testing: from zero to hero

### One-sentence summary

Detect bugs and edge cases earlier thanks to property based testing

### What's the format — is it a case study, a live coding session, a workshop or something else?

**Remote talk from France.**

Mostly a talk with slides. Possibly a bit of live coding.

### Tell us more about the talk

Property based testing has been introduced by [QuickCheck](https://hackage.haskell.org/package/QuickCheck) in Haskell years ago. It is a pretty well known technic to test apps in the functional world. Nonetheless, it is still pretty unknown outside of the functional world.

This talk will introduce the benefits that property based testing can have to increase the confidence you have in your tests. This new tool will make you able to detect unexpected bugs earlier and easily in various kinds of problems: from algorithms to ui interfaces.

Examples shown during the talk will be written using [fast-check](https://github.com/dubzzz/fast-check/), a property based testing framework written in TypeScript that already discovered bugs in some huge libraries of the JavaScript ecosystem (eg.: Jest, Jasmine). But everything can be easily adapted to other frameworks in other languages.

### A few words about yourself

Frontend software engineer for a start-up called Pigment launched in September 2019 and based in Paris. I am mostly working in TypeScript to build a React app - and sometimes a bit of C#.

Before that I have been working in C++ for 3yrs, then C# and TypeScript to build an Angular app for 2yrs.

Outside of the work, I am the author and maintainer of [fast-check](https://github.com/dubzzz/fast-check/). I did multiple talks about it and proved it useful to detect bugs in many huge libraries so I really believe it can help the whole community.

### How can we find you on social media?

GitHub: @dubzzz
Twitter: [@ndubien](https://twitter.com/ndubien)

### Would you be willing to have a Q/A session after the talk?

Yes, I'm ok for a Q/A session

### Do you mind if we record the event?

No, I'm ok if we record the event

### Is there anything we can help you with?

Nothing special

**Comment by hasparus** [comment]
oh my! the author of fast-check! I'm looking forward to the May meetup!

**Comment by karol-majewski** [comment]
Thank you @dubzzz! Looking forward to meeting you almost-in-person 😄

**Comment by dubzzz** [comment]
Very happy that the subject seems to be ok for you ;) I'd be pretty glad to meet with both of you and the community _almost-in-person_ too

**Comment by karol-majewski** [comment]
Hello again @dubzzz! Just to confirm: the meetup will take place:

- this Wednesday (May 27th, 2020)
- 6:30 pm CEST

**Requirements**

We plan on making it a Zoom call, so [Zoom](https://zoom.us/) software will be required. The link to the meetup will be shared with everyone on Wednesday. The Zoom call will start a few minutes before the actual meetup starts.

**How does this work**

Pretty simple. During the call, the speakers will be asked to share their screen and to give their talks as they would normally. We expect a few questions to be asked by the participants during the talk. It's up to the speaker to either answer them right away, answer them after the talk, or to choose not to answer them.

After the meetup, each talk will be uploaded to our YouTube channel. If you're interested in the raw video file, please let us know and we will provide it.

Please let us know if that works for you!

**Comment by dubzzz** [comment]
Thanks a lot 👍 
Perfect for me, I'll be there 😄

**Comment by karol-majewski** [comment]
https://zoom.us/s/98748834070

**Comment by beerose** [comment]
Thanks for giving the talk!

I have a quick question — are you interested in the raw video file?

**Comment by dubzzz** [comment]
Hey, thanks you so much for the organization of the meetup.
Concerning the raw video file while not, if it is easy for you to transfer it. Otherwise I'll wait for the YouTube video, if any

**Comment by karol-majewski** [comment]
Hi @dubzzz! I e-mailed you the recording. In case you haven't received it, please let me know. ;)

**Comment by dubzzz** [comment]
Thanks a lot. I've just seen the email, I will download it soon
