### ISSUE TITLE
Taking Types Too Far: Checking the Collatz Conjecture at Compile Time

### ISSUE THREAD

**Issue by ostrowr** [WrocTypeScript/talks#72]
- **Your full name**: Robbie Ostrow
- **Target audience**: everyone
- **Estimated duration**: 30-45 minutes
- **Keywords**: Collatz, turing complete, ts-json-validator, peano, typescript

# Taking Types Too Far: Checking the Collatz Conjecture at Compile Time

### One-sentence summary
We'll attempt to check the Collatz conjecture using only Typescript’s type system.

### What's the format — is it a case study, a live coding session, a workshop or something else?
Primarily slides, with frequent jaunts to the Typescript playground.

### Tell us more about the talk
This talk is based on a blog post I wrote back in December: https://ostro.ws/2019/12/09/taking-types-too-far/

This talk will build up Peano Arithmetic from scratch within the Typescript type system, where we use our newfound power to check the Collatz conjecture (well, at least for really short chains.) No prior number theory experience is required. Runtime side-effects are strictly forbidden.

If there's interest, I may also discuss using the same ideas while writing https://github.com/ostrowr/ts-json-validator

Now that I'm under quarantine, I figured it would be nice to give a remote talk!

### A few words about yourself
I'm a software engineer sheltering-in-place in San Francisco. I work for a startup called [Vanta](vanta.com) and occasionally like to abuse tools to solve tasks that they have no business solving.

### How can we find you on social media?
Website: https://ostro.ws
Github: @ostrowr

### Would you be willing to have a Q/A session after the talk?
Yep!

### Do you mind if we record the event?
I don't mind.

**Comment by karol-majewski** [comment]
How exciting! Thank you for your proposal @ostrowr.

Would that be okay if we scheduled your talk for our May event (May 27th, to be precise)?

**Comment by ostrowr** [comment]
Sounds great!

**Comment by karol-majewski** [comment]
Excellent! May it is then. Looking forward to it.

**Comment by karol-majewski** [comment]
Hello again @ostrowr! Just to confirm: the meetup will take place:

- this Wednesday (May 27th, 2020)
- 6:30 pm CEST

**Requirements**

We plan on making it a Zoom call, so [Zoom](https://zoom.us/) software will be required. The link to the meetup will be shared with everyone on Wednesday. The Zoom call will start a few minutes before the actual meetup starts.

**How does this work**

Pretty simple. During the call, the speakers will be asked to share their screen and to give their talks as they would normally. We expect a few questions to be asked by the participants during the talk. It's up to the speaker to either answer them right away, answer them after the talk, or to choose not to answer them.

After the meetup, each talk will be uploaded to our YouTube channel. If you're interested in the raw video file, please let us know and we will provide it.

Please let us know if that works for you!

**Comment by ostrowr** [comment]
Yep, all sounds good. Looking forward!

**Comment by beerose** [comment]
Thank you for your talk! 

I have a quick question — are you interested in the raw video file?

**Comment by ostrowr** [comment]
Sure, thanks!

**Comment by ostrowr** [comment]
Thanks so much; this was fun! Looking forward to seeing future talks.

**Comment by karol-majewski** [comment]
Hi @ostrowr! I just e-mailed you the recording. In case you haven't received it, please let me know. ;)

**Comment by ostrowr** [comment]
Got it, thanks!
