### ISSUE TITLE
Autocomplete XState and anything in between

### ISSUE THREAD

**Issue by krzysztofzuraw** [WrocTypeScript/talks#74]
- **Your full name**: Krzysztof Żuraw
- **Target audience** (intermediate/):
- **Estimated duration**: how much time do I have?
- **Keywords**: xstate, autocomplete, TypeScript, react, mapbox, tailwindcss, side project

# Autocomplete XState and anything in between

### One-sentence summary
What I learn from building autocomplete with xstate

### What's the format — is it a case study, a live coding session, a workshop or something else?
case study of side project

### Tell us more about the talk
I want to talk about more complex projects done in xstate. It will
be about invoking promises, observables from xstate, how to hook it into React, how to write unit tests. Everything in TypeScript. I have planned to talk about what is nice about xstate
and what is not. Note: I may add a few things when I think it more through 😃.

### A few words about yourself
🏗️ Frontend | Design: Learning | Coffee 🦄
Frontend: React & TypeScript | Design: Learning | Coffee: from Chemex

Long (copy & pasted from my website - https://krzysztofzuraw.com):
I'm self-taught frontend developer working at Ingrid. I enjoy working with TypeScript, React, Redux and RxJs. Previously I was coding in Python (mainly Django framework). I have a blog at https://krzysztofzuraw.com

If I'm not coding I like to brew some good coffee with Chemex or Aeropress. You can also find me in various food spots (tasty ones) around Wrocław. I also like giving back to community so a few times I was a mentor on Django Girls (Wrocław & Kraków) and used to teach Python at Code Geeks Carrots Wrocław.

I like to organize things. I'm coorganizer of Wrocław TypeScript meetup. I'm helping in coordination of Django Girls Wrocław. If you need a place & help with preparing some event do not hesitate to contact me.

### How can we find you on social media?
Please use links from here: https://keybase.io/krzysztofzuraw/. I wanted to post
my filmweb account but I forgot my password 😞.
### Would you be willing to have a Q/A session after the talk?
Yes
### Do you mind if we record the event?
No
### Is there anything we can help you with?
Schedule my talk in the nearest future

**Comment by karol-majewski** [comment]
Thank you @krzysztofzuraw!

The recording is now on YouTube: https://www.youtube.com/watch?v=7CP-OUcUq2Q
