### ISSUE TITLE
What is Deno and will it replace Node.js?

### ISSUE THREAD

**Issue by kajetansw** [WrocTypeScript/talks#76]
- **Your full name**: Kajetan Świątek
- **Target audience**: everyone
- **Estimated duration**: 20min
- **Keywords**: Deno, Node.js, Back-end

# What is Deno and will it replace Node.js?

## The talk

Brief overview of what Deno is, what problems does it solve and how to use it.

### What's the format — is it a case study, a live coding session, a workshop or something else?

Presentation + short live coding session.

### Tell us more about the talk

Deno is here! May 2020 marked the official premiere of Deno 1.0 and created major uproar among Node.js users and the JavaScript community.

What is it? How it works? What features does it have? How to use it? And more importantly: Will it replace Node.js on its throne?

This presentation serves as a brief overview of the technology with a short live coding session included.

### A few words about yourself

Former construction engineer, now building software instead. Front-end developer at Aptitude Software. Recent functional programming enthusiast. Hears coding buzzwords from a mile away and comes right away to join the talk.

### How can we find you on social media?

Twitter [@kajetansw](http://www.twitter.com/kajetansw)

### Would you be willing to have a Q/A session after the talk?

Sure, I'll do my best.

### Do you mind if we record the event?

Not at all.

### Is there anything we can help you with?

Nothing I can think of, thanks ;)

**Comment by karol-majewski** [comment]
Sold! Booked for June.

**Comment by karol-majewski** [comment]
Thank you @kajetansw!

The recording is now on YouTube: https://www.youtube.com/watch?v=nheSLk6pwR0
