### ISSUE TITLE
WIP: Building a branded styling DSL in TypeScript 

### ISSUE THREAD

**Issue by hasparus** [WrocTypeScript/talks#78]
- **Your full name**: Piotr Monwid-Olechnowicz
- **Target audience** (beginner/intermediate/advanced/everyone): everyone
- **Estimated duration**: 5-10 minutes, not sure yet.
- **Keywords**: styling, dsl, css, emotion, theme-ui, constraint-based design

# Building a branded styling DSL in TypeScript 

### One-sentence summary

**TBD**

### What's the format — is it a case study, a live coding session, a workshop or something else?

a really small case study I guess?

### Tell us more about the talk

**TBD**

### A few words about yourself

A software gardener, laptop hobo, amateur open source contributor, note-taker, coffee and whisky drinker.

### How can we find you on social media?

https://twitter.com/hasparus

### Would you be willing to have a Q/A session after the talk?

✅

### Do you mind if we record the event?

nope

### Is there anything we can help you with?

I'm fine.

**Comment by karol-majewski** [comment]
Your lucky day @hasparus! We may have a slot for you this month. :trollface:

**Comment by hasparus** [comment]
> Your lucky day @hasparus! We may have a slot for you this month. :trollface:


What a coincidence! 😮

**Comment by karol-majewski** [comment]
🤫

**Comment by karol-majewski** [comment]
Thank you and come back next time!
