### ISSUE TITLE
Cross browser testing & automation with Puppeteer and TypeScript

### ISSUE THREAD

**Issue by meerasndr** [WrocTypeScript/talks#81]
- **Your full name**: Meera Sundar
- **Target audience** (beginner/intermediate/advanced/everyone): Everyone
- **Estimated duration**: 20 minutes
- **Keywords**: headless browser testing, puppeteer, chromium

# Cross browser testing & automation with Puppeteer and TypeScript

**Comment by karol-majewski** [comment]
Package received! Your talk [has been announced on Twitter](https://twitter.com/WrocTypeScript/status/1305616806325952512).

Thank you for your contribution!

**Comment by karol-majewski** [comment]
Thank you! 🌷 ❤️ 

You can find your talk on YouTube: https://www.youtube.com/watch?v=Mmnwv5kr7No
