### ISSUE TITLE
Rapid and type-safe Node.js development with Prisma

### ISSUE THREAD

**Issue by 2color** [WrocTypeScript/talks#82]
- **Daniel Norman**:
- **everyone** (beginner/intermediate/advanced/everyone):
- **25-30 minutes**:

# Rapid and type-safe Node.js development with Prisma

### One-sentence summary

An introduction to Prisma and a look at how it solves common problems when working with relational databases.

### What's the format — is it a case study, a live coding session, a workshop or something else?

Presentation with some live coding

### Tell us more about the talk

For developers that embrace rapid development, working with relational databases comes with a lot of challenges. But it’s possible to optimize for developer experience without compromising on reliability with Prisma – an open-source end-to-end type-safe database toolkit for TypeScript and Node.js. In this talk, we'll introduce Prisma and learn how it enables rapid and type-safe development while addressing common problems in data-centric applications.

### A few words about yourself

Daniel is a software engineer with broad experience across modern web and cloud environments. He's passionate about open source and modern development tooling and likes bringing ideas from different disciplines to software development. These days, Daniel is a developer advocate at Prisma, focusing on modern database tooling for Node.js and Typescript. Outside the software world, Daniel is interested in woodworking and motorcycling.

### How can we find you on social media?

https://twitter.com/daniel2color
https://github.com/2color

### Would you be willing to have a Q/A session after the talk?

Would love to

### Do you mind if we record the event?

No. That's fine!

**Comment by karol-majewski** [comment]
Thank you for the proposal @2color! 

Are you interested in giving your talk during our September meetup (Sep 30th, 18:30 CEST)?

**Comment by 2color** [comment]
> Are you interested in giving your talk during our September meetup (Sep 30th, 18:30 CEST)?

Yes

**Comment by karol-majewski** [comment]
Great, adding it to the event then. Thanks!

**Comment by 2color** [comment]
Wonderful! Thanks

**Comment by beerose** [comment]
Hi @2color!

The meetup will take place in a few hours and I just wanted to let you know about a few things.

It will be over a zoom call and you can find a link here: https://www.meetup.com/WrocTypeScript/events/sjzhvqybcmbfc/. We'll be there 15-20 minutes early. 

There will be time for questions after the talk, but some people may ask questions during your talk — it's up to you whether you want to answer them right away or later. 

Let me know if you have any questions! 🙂

**Comment by 2color** [comment]
Sounds good Aleksandra! Looking forward.

**Comment by 2color** [comment]
@beerose Will the talk be recorded and available after?

**Comment by beerose** [comment]
@2color Yes, it will be recorder and uploaded to our YouTube channel. If you're interested in the raw video file, please let us know and we will provide it.

**Comment by karol-majewski** [comment]
Thank you! 🤗 ❤️ 

You can find your talk on YouTube: https://www.youtube.com/watch?v=ddGvGm00ny8

**Comment by 2color** [comment]
Thanks @karol-majewski!
