### ISSUE TITLE
Earl - typesafe assertion library

### ISSUE THREAD

**Issue by krzkaczor** [WrocTypeScript/talks#84]
- **Your full name**: Krzysztof Kaczor
- **Target audience** (beginner/intermediate/advanced/everyone): intermediate
- **Estimated duration**: 20-30min
- **Keywords**: testing, assertions, type safety, mocha

# Earl - typesafe assertion library

### One-sentence summary

Learn how we designed a typesafe assertion library for node.js and not went crazy

### What's the format — is it a case study, a live coding session, a workshop or something else?

Regular presentation

### Tell us more about the talk

Earl is the first TypeScript first assertion library for node. While developing it we tackled some interesting issues like:
- expressing in types incorrect assertions,
- TS 3.7's assertion functions,
- dynamically extending interfaces with plugins,
and more...

### A few words about yourself

In the past, Krzysztof created some quite popular TypeScript libraries like [`ts-essentials`](https://github.com/krzkaczor/ts-essentials) and [`TypeChain`](https://github.com/ethereum-ts/TypeChain). Currently on a quest of creating a decent assertion library for node.js.

### How can we find you on social media?

https://twitter.com/krzKaczor
https://github.com/krzkaczor

### Would you be willing to have a Q/A session after the talk?

Sure!

### Do you mind if we record the event?

Not, not at all

### Is there anything we can help you with?

Nopeeeee

**Comment by karol-majewski** [comment]
SOLD. Thank you for the contribution @krzkaczor
