### ISSUE TITLE
Documentation FAQs request: are remote talks ok right now?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [WrocTypeScript/talks#86]
I'd love to speak, but can only come remote right now. I didn't see any docs in the README.md about whether you host remote meetings or are ok with remote speakers. Is that still a thing?

Sorry if this issue form is meant to be _exclusively_ for talks!

**Comment by beerose** [comment]
Hey @JoshuaKGoldberg! 

We were hosting online meetups for a few months after the pandemic started, but then we stopped 😬 

There were some attempts to bring the meetup back (in person), but everyone got busy, and we couldn't find a new sponsor, so nothing came out of it (yet!). If we host Wroc TS meetups again (either online or in-person), I'll let you know! Even if we go with in-person, I think it'll be okay for you to join it online or do a prerecorded talk (or prerecorded talk + live q&a).

**Comment by JoshuaKGoldberg** [comment]
Super thanks, I appreciate the quick response!

**Comment by karol-majewski** [comment]
Thanks for reaching out @JoshuaKGoldberg!

We might have found a new sponsor. It's nothing official yet, but if it's finalized, we'll be able to host physical brick & mortar meetups with the possibility for remote speakers to join us live. I'm looking forward to having _you_ give a talk!

cc @krzysztofzuraw
