### ISSUE TITLE
Reverse Mapped Types - today and in the future

### ISSUE THREAD

**Issue by Andarist** [WrocTypeScript/talks#88]
- **Your full name**: Mateusz Burzyński
- **Target audience** Advanced
- **Estimated duration**: 45min
- **Keywords**: reverse mapped types, type gymnastics

# Reverse Mapped Types - today and in the future

### One-sentence summary

Learn how to utilize the little-known reverse mapped types to create types specific to a particular key in the object or a tuple position.

### What's the format — is it a case study, a live coding session, a workshop or something else?

Usage examples

### Tell us more about the talk

1. Short recap of what mapped types are
2. What the heck are reverse mapped types
3. Basic example
4. 2 advanced example
5. Limitations and how they could be lifted in the future

### A few words about yourself

My name is Mateusz Burzyński and I'm a JavaScript developer focused on React. I'm also a big OSS enthusiast. I believe that node_modules is not a black box and I dive into it frequently. I maintain XState, Emotion, Redux-Saga, Changesets and I contribute to TypeScript itself.

### How can we find you on social media?

https://twitter.com/AndaristRake

### Would you be willing to have a Q/A session after the talk?

Yes

### Do you mind if we record the event?

No

### Is there anything we can help you with?

Review the slides/talk outline before the event

**Comment by krzysztofzuraw** [comment]
Thanks @Andarist for proposal and looking forward to having you on Wrocław TypeScript 🥳

**Comment by beerose** [comment]
Hey @Andarist! Could we have a picture of you that you'd like us to use for all the marketing stuff?

**Comment by Andarist** [comment]
@beerose can u grab the one from my Twitter profile? The handle there is AndaristRake

**Comment by beerose** [comment]
> @beerose can u grab the one from my Twitter profile? The handle there is AndaristRake

Sure! thanks!

**Comment by karol-majewski** [comment]
Thank you again, @Andarist!

**Comment by Andarist** [comment]
For anyone interested, you can find all of the discussed playgrounds [here](https://gist.github.com/Andarist/0294519c570a52fb14f4cdd3d589c880)
